### ISSUE TITLE
Error on startup. Unrecognized option '-wnetwork'

### ISSUE THREAD

**Issue by vxxce** [featurecat/lizzie#117]
When I run lizzie.jar from command prompt I get the following error:

```
Creating config file
time_left b 0 0
ERROR: unrecognised option '-wnetwork'
Leelaz process ended.
```
Maybe I'm just doing something wrong, but I think the commandline option is meant to be just `-w` and not `-wnetwork`. Could not find the problem anywhere.

**Comment by featurecat** [comment]
is this version 0.3 official release, or compiled from this branch?

**Comment by vxxce** [comment]
official release.

**Comment by featurecat** [comment]
what operating system? have you modified anything or gotten it to work at all?

**Comment by vxxce** [comment]
Windows 10. I replaced leelaz.exe with another leela engine, but otherwise did not modify anything. Previously, I tried to use Lizzie and was unable to until I switched out the leelaz.exe file. This worked for me last time. So, this time, I attempted the same thing. When I received the original error `unrecognised option '-wnetwork'` I tried other leela engines (including the original one that came with the release, older versions, and the commandline engine-only version).

So far, no luck. Any ideas?

**Comment by featurecat** [comment]
Please try this jar which may solve the problem: [here](https://drive.google.com/open?id=14Kv4kX7GCCDtILns4qXn17EQXcwxuGjI)

Please let me know if it solves the issue as soon as possible. Then I may update the release to fix this bug.

**Comment by vxxce** [comment]
The provided jar gave NullPointerExceptions:

```
Exception in thread "main" java.lang.NullPointerException
        at wagner.stephanie.lizzie.plugin.PluginManager.loadPlugins(PluginManager.java:25)
        at wagner.stephanie.lizzie.Lizzie.main(Lizzie.java:39)
```

**Comment by featurecat** [comment]
oh... the program may not have write access. try running in administrative mode

**Comment by featurecat** [comment]
Did that fix the issue?

**Comment by vxxce** [comment]
Almost? Lizzie opened very briefly and then terminated. It did create the config file, but that's it. That's using the leela engine and all original files from the most recent release (with the provided replacement jar). Repeating the command gives no errors/exceptions, only says leelaz process has ended.

If I swap the engine out for other versions of leela, I get the following exception:

```
C:\Program Files\lizzie>java -jar Lizzie-issue117.jar
Exception in thread "main" java.lang.IllegalStateException: Buffers have not been created
        at java.desktop/sun.awt.windows.WComponentPeer.getBackBuffer(Unknown Source)
        at java.desktop/java.awt.Component$FlipBufferStrategy.getBackBuffer(Unknown Source)
        at java.desktop/java.awt.Component$FlipBufferStrategy.updateInternalBuffers(Unknown Source)
        at java.desktop/java.awt.Component$FlipBufferStrategy.createBuffers(Unknown Source)
        at java.desktop/java.awt.Component$FlipBufferStrategy.<init>(Unknown Source)
        at java.desktop/java.awt.Component$FlipSubRegionBufferStrategy.<init>(Unknown Source)
        at java.desktop/java.awt.Component.createBufferStrategy(Unknown Source)
        at java.desktop/java.awt.Window.createBufferStrategy(Unknown Source)
        at java.desktop/java.awt.Component.createBufferStrategy(Unknown Source)
        at java.desktop/java.awt.Window.createBufferStrategy(Unknown Source)
        at wagner.stephanie.lizzie.gui.LizzieFrame.<init>(LizzieFrame.java:111)
        at wagner.stephanie.lizzie.Lizzie.main(Lizzie.java:43)
Leelaz process ended.
```

**Comment by featurecat** [comment]
yes do not swap out the Leelaz file. it must be the one you compiled or received with lizzie.

did you download the network file from zero.sjeng.org/best-network? did you remember to unzip that file and then rename the unzipped network to "network"?

**Comment by vxxce** [comment]
Looks like I was just unzipping the .gz network file incorrectly. Didn't know what I was doing with 7-zip! Thanks for the help.
