### ISSUE TITLE
Lizzie is not loading. Windows x64

### ISSUE THREAD

**Issue by TDonets** [featurecat/lizzie#139]
Eternal loading. I checked that all the prerequisites are met. Leelaz file is in the folder. 

C:\Users\Tim>java -jar C:\Users\Tim\Documents\lizzie\lizzie.jar
java.io.IOException: Cannot run program "./leelaz" (in directory "."): CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(Unknown Source)
        at wagner.stephanie.lizzie.analysis.Leelaz.<init>(Leelaz.java:98)
        at wagner.stephanie.lizzie.Lizzie.lambda$main$0(Lizzie.java:32)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 4 more
javax.imageio.IIOException: Can't read input file!
        at javax.imageio.ImageIO.read(Unknown Source)
        at wagner.stephanie.lizzie.theme.DefaultTheme.getBackground(DefaultTheme.java:61)
        at wagner.stephanie.lizzie.gui.LizzieFrame.createBackground(LizzieFrame.java:309)
        at wagner.stephanie.lizzie.gui.LizzieFrame.paint(LizzieFrame.java:232)
        at javax.swing.RepaintManager$4.run(Unknown Source)
        at javax.swing.RepaintManager$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.access$1200(Unknown Source)
        at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at wagner.stephanie.lizzie.gui.LizzieFrame.createBackground(LizzieFrame.java:310)
        at wagner.stephanie.lizzie.gui.LizzieFrame.paint(LizzieFrame.java:232)
        at javax.swing.RepaintManager$4.run(Unknown Source)
        at javax.swing.RepaintManager$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.access$1200(Unknown Source)
        at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
javax.imageio.IIOException: Can't read input file!
        at javax.imageio.ImageIO.read(Unknown Source)
        at wagner.stephanie.lizzie.theme.DefaultTheme.getBoard(DefaultTheme.java:49)
        at wagner.stephanie.lizzie.gui.BoardRenderer.drawWoodenBoard(BoardRenderer.java:460)
        at wagner.stephanie.lizzie.gui.BoardRenderer.drawBackground(BoardRenderer.java:129)
        at wagner.stephanie.lizzie.gui.BoardRenderer.draw(BoardRenderer.java:71)
        at wagner.stephanie.lizzie.gui.LizzieFrame.paint(LizzieFrame.java:253)
        at javax.swing.RepaintManager$4.run(Unknown Source)
        at javax.swing.RepaintManager$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.access$1200(Unknown Source)
        at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
javax.imageio.IIOException: Can't read input file!
        at javax.imageio.ImageIO.read(Unknown Source)
        at wagner.stephanie.lizzie.theme.DefaultTheme.getBoard(DefaultTheme.java:49)
        at wagner.stephanie.lizzie.gui.BoardRenderer.drawWoodenBoard(BoardRenderer.java:461)
        at wagner.stephanie.lizzie.gui.BoardRenderer.drawBackground(BoardRenderer.java:129)
        at wagner.stephanie.lizzie.gui.BoardRenderer.draw(BoardRenderer.java:71)
        at wagner.stephanie.lizzie.gui.LizzieFrame.paint(LizzieFrame.java:253)
        at javax.swing.RepaintManager$4.run(Unknown Source)
        at javax.swing.RepaintManager$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.access$1200(Unknown Source)
        at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by dfannius** [comment]
Is the Leela Zero executable in that directory named `leelaz` or `leelaz.exe`?

**Comment by TDonets** [comment]
just named leelaz

**Comment by dfannius** [comment]
Try renaming it to `leelaz.exe` and running Lizzie again.

Probably we should have Lizzie exit more cleanly with these sorts of issues (e.g., missing/invalid network weights files) instead of barfing so it's more clear what's going on.

**Comment by featurecat** [comment]
FWIW even on windows, "./leelaz" seems to execute leelaz.exe. but I don't know if windows let's you execute things that don't end in .exe (maybe to prevent malicious scripts disguising them as other files?)

could you please send a screenshot of your lizzie directory?

**Comment by TDonets** [comment]
So, after renaming leelaz to leelaz.exe nothing changed, error log is the same. 
Here is the screenshot: http://prntscr.com/ja1j0b

**Comment by featurecat** [comment]
I see the problem. There are in fact two problems.

You are running this command from C:/Users/Tim, but Lizzie's directory is in C:\Users\Tim\Documents\lizzie

**Comment by TDonets** [comment]
Oh okay, I am far from using the cmd. Here is the next try
C:\Users\Tim\Documents\lizzie>java -jar C:\Users\Tim\Documents\lizzie\lizzie.jar
Creating config file
java.io.IOException: Cannot run program "./leelaz" (in directory "."): CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(Unknown Source)
        at wagner.stephanie.lizzie.analysis.Leelaz.<init>(Leelaz.java:98)
        at wagner.stephanie.lizzie.Lizzie.lambda$main$0(Lizzie.java:32)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 4 more

**Comment by TDonets** [comment]
After renaming leelaz.exe to leelaz back. Here is the new error:
C:\Users\Tim\Documents\lizzie>java -jar C:\Users\Tim\Documents\lizzie\lizzie.jar
Leelaz process ended.
java.io.IOException: Problem reading font data.
        at java.awt.Font.createFont0(Unknown Source)
        at java.awt.Font.createFont(Unknown Source)
        at wagner.stephanie.lizzie.gui.LizzieFrame.<clinit>(LizzieFrame.java:87)
        at wagner.stephanie.lizzie.Lizzie.main(Lizzie.java:43)

**Comment by featurecat** [comment]
Did you do what I said to do with the network file? How large is that file in Kb?

**Comment by TDonets** [comment]
There is no comment from you about the network, sorry. The size is 38 997 Kb.

**Comment by featurecat** [comment]
> The second problem is you have not unzipped the network file. This is a mistake in the readme.txt, I hope to update it some time soon. You should unzip it with a utility like 7zip (or winzip would also work). Then the resulting .txt file should be named "network" with no file extension.

**Comment by TDonets** [comment]
Great catch! Thank you. Now it is only this error with fonts.

**Comment by featurecat** [comment]
ok. then we can definitely get it working now.  one second ill find the jar u need

**Comment by featurecat** [comment]
So replace Lizzie.jar with [this alternate Lizzie.jar](https://drive.google.com/open?id=1v2OJQ1w3OK7cb8sqJPuFIo6qhG84aZV_). It will work. I am just not sure why users are getting the Font issue especially since Lizzie works fine on my own Windows computer. :/

**Comment by TDonets** [comment]
Welp, now it says this:
C:\Users\Tim\Documents\lizzie>java -jar C:\Users\Tim\Documents\lizzie\lizzie.jar
Leelaz process ended.

**Comment by featurecat** [comment]
ok... please screenshot your directory again now that we've changed some things?

**Comment by TDonets** [comment]
Sure thing, here you go. And thank you very much for helping me!
http://prntscr.com/ja26qu

**Comment by featurecat** [comment]
Click view, check the box that says "File Name Extensions". NOW rename the entire network name to "network". You have it as a text document, which lizzie cannot comprehend. This is so involved, right? It gives me some ideas for next version. Hopefully installation will be seamless at that point.

**Comment by TDonets** [comment]
It works!!! Wohooo! Thank you a ton for support and for your work!

**Comment by featurecat** [comment]
Yay! I'm so glad. Could you please help me out just to figure out if there is a bug?

Rename Lizzie.jar to Lizzie2.jar.
Copy Lizzie.jar from the original release to your Lizzie directory, and try running it this time, now that you have the correct network file.

Does it work? If so, I'd recommending using that one since the fonts are better. If it doesn't, please give me the error message :)

**Comment by TDonets** [comment]
Okay, just a sec

**Comment by featurecat** [comment]
yes! so I guess it's not a bug although I'm so confused why it generates that exception. just use that jar. thanks :)
