### ISSUE TITLE
Error: Program is loading Leela forever...

### ISSUE THREAD

**Issue by weiqi5** [featurecat/lizzie#150]
When I start (by double click), the program displays background (nice nature photo!) and goban and says: "Leela Zero is loading..." Then nothing happens, even after 15 minutes.
Starting in the console gives these error messages:

Exception in thread "main" java.lang.UnsupportedClassVersionError: wagner/stephanie/lizzie/Lizzie : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

Then nothing happens. 

Can somebody help?

My system: OS X 10.11.6
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4833)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)

**Comment by featurecat** [comment]
please update Java to the latest version.

**Comment by featurecat** [comment]
If you're on Windows, it should already be included. If you're on Mac/Linux, you need to compile it according to the directions. Since you're on Mac, follow the instructions in the README of our repository to compile.
