### ISSUE TITLE
Error when launching - FIXED: by removing .txt extention from the network file

### ISSUE THREAD

**Issue by knodakip** [featurecat/lizzie#151]
Hi,

First, thanks a lot for the hard work! I (and I believe the whole community) really appreciate!

I have issues running the new lizzie v0.4; in the console the following two message appears:
_Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: boardLength may not be less than 18, but was 0
        at wagner.stephanie.lizzie.gui.BoardRenderer.calculatePixelMargins(BoardRenderer.java:486)
        at wagner.stephanie.lizzie.gui.BoardRenderer.calculatePixelMargins(BoardRenderer.java:712)
        at wagner.stephanie.lizzie.gui.BoardRenderer.convertScreenToCoordinates(BoardRenderer.java:758)
        at wagner.stephanie.lizzie.gui.LizzieFrame.onMouseMoved(LizzieFrame.java:555)
        at wagner.stephanie.lizzie.gui.Input.mouseMoved(Input.java:56)
        at java.awt.Component.processMouseMotionEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Window.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Leelaz process ended._

EDIT: Now I get the following error:
_Leelaz process ended.
java.io.IOException: Problem reading font data.
        at java.awt.Font.createFont0(Unknown Source)
        at java.awt.Font.createFont(Unknown Source)
        at wagner.stephanie.lizzie.gui.LizzieFrame.<clinit>(LizzieFrame.java:87)
        at wagner.stephanie.lizzie.Lizzie.main(Lizzie.java:43)_

Any idea how I can fix this? Sorry for the stupid question, I am not familiar at all with Java and programming.
I am using Java version 8 (build 1.8.0_171-b11) on Windows 10

Kind regards;
François

**Comment by featurecat** [comment]
The problem is related to the network file. You need to download the best-network from zero.sjeng.org/best-network, unzip the resulting .gz file with 7-zip (7-zip.org), and either: rename the resulting .txt file to "network" WITHOUT the .txt extension (to see how to do this in Windows, see #139), or rename the network file in lizzie.properties.

**Comment by knodakip** [comment]
Hi featurecat,

Thank you so much for the help, this now works :)

Best,
François

**Comment by featurecat** [comment]
glad :)
