### ISSUE TITLE
Not running on OSX

### ISSUE THREAD

**Issue by elensar92** [featurecat/lizzie#215]
Version = OS X 10.13.3
I tried to run Lizzie(release version) on OSX 

compiled leelaz(featurecat version)
and copy it to lizzie folder and copy network file on same folder

but it closed just after I did double-click leezie.jar file

No error message.

**Comment by elensar92** [comment]
lizzie cenovis$ java -jar Lizzie.jar
java.io.IOException: Stream closed
	at java.base/java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:442)
	at java.base/java.io.OutputStream.write(OutputStream.java:113)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:143)
	at wagner.stephanie.lizzie.analysis.Leelaz.sendCommand(Leelaz.java:280)
	at wagner.stephanie.lizzie.analysis.Leelaz.isCorrectVersion(Leelaz.java:122)
	at wagner.stephanie.lizzie.analysis.Leelaz.<init>(Leelaz.java:102)
	at wagner.stephanie.lizzie.Lizzie.lambda$main$0(Lizzie.java:32)
	at java.base/java.lang.Thread.run(Thread.java:844)
Leelaz process ended.

**Comment by featurecat** [comment]
try compiling it for cpu only. find Config.h in the Leelaz src, comment out the line with USE_OPENCL (something like that), and recompile.
