### ISSUE TITLE
Lizzie doesnt work at all

### ISSUE THREAD

**Issue by melivan73** [featurecat/lizzie#224]
Hello.
Downloaded v0.3 gpu release, tried different networks. Doesnt work at all. It creates lizzie.properties file and nothing happens. (if start from console, says "Leelaz process ended"). 
Absolutely same for v0.4 gpu and cpu releases. 
Interesting that if I replace provided leelaz.exe with file downloaded from http://zero.sjeng.org/ then it starts ui but says that leelaz incompatible with lizzie (v 1.04).
Another interesting thing that in all versions lizzie.properties has "gpu": []. Tried to put 0 or 1 inside the brackets  - doesnt help.
My configuration AMD X4 760, NVidia GTX 660, Win 7 64bit, Java 10 for 64x Win.

**Comment by l1t1** [comment]
try java 8

**Comment by melivan73** [comment]
Tried Java Version 8 Update 171 for 64bit - doesnt help.

**Comment by featurecat** [comment]
Could you please set 'print-comms' to true in v0.4, and show me all the output generated? Thanks.

**Comment by melivan73** [comment]
set 'print-comms' to true, but I cant see any output. Should it be created in lizzie folder?
I could provide teamviewer access to my PC if you could help. 
'visual studio 2015 redistributable installed.

**Comment by featurecat** [comment]
could you see if installing the latest version of Lizzie helps? we will release in a few days.

**Comment by Aerospace91** [comment]
Set Print Comms to true and got this

C:\lizzie>java -jar lizzie.jar
> time_left B 0 0
java.io.IOException: The pipe is being closed
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(Unknown Source)
        at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
        at java.io.BufferedOutputStream.flush(Unknown Source)
        at java.io.BufferedOutputStream.flush(Unknown Source)
        at wagner.stephanie.lizzie.analysis.Leelaz.sendCommand(Leelaz.java:280)
        at wagner.stephanie.lizzie.analysis.Leelaz.isCorrectVersion(Leelaz.java:122)
        at wagner.stephanie.lizzie.analysis.Leelaz.<init>(Leelaz.java:102)
        at wagner.stephanie.lizzie.Lizzie.lambda$main$0(Lizzie.java:32)
        at java.lang.Thread.run(Unknown Source)
Leelaz process ended.
java.io.IOException: Problem reading font data.
        at java.awt.Font.createFont0(Unknown Source)
        at java.awt.Font.createFont(Unknown Source)
        at wagner.stephanie.lizzie.gui.LizzieFrame.<clinit>(LizzieFrame.java:87)
        at wagner.stephanie.lizzie.Lizzie.main(Lizzie.java:43)

C:\lizzie>

**Comment by featurecat** [comment]
You haven't extracted the network file or haven't renamed it to be without a file extension. You can either fix that or wait for the next version of Lizzie in a few days which will handle this automatically.

**Comment by melivan73** [comment]
Just found the problem, have had some mess with installation VC++ redistributable packages. Reinstalled them and it works!
Thanks for support.

**Comment by featurecat** [comment]
thank you for posting your solution!
