### ISSUE TITLE
Lizzie not working on windows

### ISSUE THREAD

**Issue by DaveTheShark** [featurecat/lizzie#228]
I've tried a couple times to get lizzie working on windows now, but every time it opens for a minute then closes itself. Here's the output from the command line.

![screenshot 2018-05-19 15 00 54](https://user-images.githubusercontent.com/39437924/40269436-730a3e7e-5b76-11e8-8cc3-8dcd23270cb4.png)

**Comment by Sung-June** [comment]
me too

**Comment by kaorahi** [comment]
I noticed that the same "IllegalArgumentException" was also reported in #121, #151, and #163.
So I tried an experiment, though I am not sure whether this is essential to the current issue.

(A) I get "IllegalArgumentException" if I add the following line (1) into "main" in Lizzie.java:

            frame = new LizzieFrame();
            frame.onMouseMoved(111, 222);  // (1)

(B) The exception disappears if I add the following line (2):


            frame = new LizzieFrame();
            frame.paint(null);             // (2)
            frame.onMouseMoved(111, 222);  // (1)

The console output in (A) is as follows.

    Exception in thread "main" java.lang.IllegalArgumentException: boardLength may not be less than 18, but was 0
            at wagner.stephanie.lizzie.gui.BoardRenderer.calculatePixelMargins(BoardRenderer.java:565)
            at wagner.stephanie.lizzie.gui.BoardRenderer.calculatePixelMargins(BoardRenderer.java:793)
            at wagner.stephanie.lizzie.gui.BoardRenderer.convertScreenToCoordinates(BoardRenderer.java:839)
            at wagner.stephanie.lizzie.gui.LizzieFrame.onMouseMoved(LizzieFrame.java:682)
            at wagner.stephanie.lizzie.Lizzie.main(Lizzie.java:37)

**Comment by featurecat** [comment]
so this exception is totally harmless. I will remove it / prevent it from happening. I'm not sure what's happening here. what's the programs behavior leading up the crash? you said it takes a minute sometimes?

**Comment by DaveTheShark** [comment]
Sometimes the UI opens up and it says loading before suddenly closing, as you can see the first time I ran it there was no error but it just shut down. The second time it opened a white screen then shut down without displaying anything and I had the error message.

**Comment by DonMathi** [comment]
There is different in the startup behaviour denpending on if "automatically-download-latest-network": is set false or true. When false then the GUI does not show, but when true the GUI comes up briefly then shuts down again

**Comment by featurecat** [comment]
try deleting network.gz and Config.txt

**Comment by featurecat** [comment]
what's the output when run via command line?

**Comment by DonMathi** [comment]
Exception in thread "AWT-EventQueue-0" java.lang.ArithmeticException: / by zero
        at featurecat.lizzie.gui.BoardRenderer.convertScreenToCoordinates(BoardRenderer.java:943)
        at featurecat.lizzie.gui.LizzieFrame.onMouseMoved(LizzieFrame.java:816)
        at featurecat.lizzie.gui.Input.mouseMoved(Input.java:59)
        at java.awt.Component.processMouseMotionEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Window.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Leelaz process ended.

**Comment by DonMathi** [comment]
Exception in thread "Thread-3" java.lang.IllegalStateException: No match found
        at java.util.regex.Matcher.group(Unknown Source)
        at featurecat.lizzie.analysis.Leelaz.getBestNetworkHash(Leelaz.java:142)
        at featurecat.lizzie.analysis.Leelaz.needToDownloadLatestNetwork(Leelaz.java:154)
        at featurecat.lizzie.analysis.Leelaz.updateToLatestNetwork(Leelaz.java:112)
        at featurecat.lizzie.analysis.Leelaz.<init>(Leelaz.java:82)
        at featurecat.lizzie.Lizzie.lambda$main$0(Lizzie.java:38)
        at java.lang.Thread.run(Unknown Source)

**Comment by DonMathi** [comment]
I tried deleting the files, and restoring them. Now the GUI hangs with "Loading"

**Comment by featurecat** [comment]
how long loading? it might be downloading the network.

**Comment by DonMathi** [comment]
now tried to delete the files, run Lizzie, edit config to set load newest to true. run Lizzie again, and now it hangs with 
Exception in thread "Thread-3" java.lang.IllegalStateException: No match found
        at java.util.regex.Matcher.group(Unknown Source)
        at featurecat.lizzie.analysis.Leelaz.getBestNetworkHash(Leelaz.java:142)
        at featurecat.lizzie.analysis.Leelaz.updateToLatestNetwork(Leelaz.java:115)
        at featurecat.lizzie.analysis.Leelaz.<init>(Leelaz.java:82)
        at featurecat.lizzie.Lizzie.lambda$main$0(Lizzie.java:38)
        at java.lang.Thread.run(Unknown Source)

**Comment by DonMathi** [comment]
loading and loading and loading

**Comment by featurecat** [comment]
OK. download the best network from zero.sjeng.org/best-network and name it network.gz. place it in lizzie directory. what's the command line output?

**Comment by DonMathi** [comment]
just hangs in loading

**Comment by featurecat** [comment]
so there's no output even when you have the network downloaded already? try enabling print comms to true?

**Comment by DonMathi** [comment]
With download=false and print_comms=true:
> 1 version
> 2 lz-analyze 10
Leelaz process ended.

**Comment by featurecat** [comment]
OK... that's really weird. could you send a screenshot of your lizzie directory? also did you update Leela zero? it must be compiled from the current next branch. what's your operating system?

**Comment by DonMathi** [comment]
Ok, down have more time right now. I just downloaded the 0.5 version. No special compile. I think I must try that next when I got the time

**Comment by featurecat** [comment]
OK. sorry that we couldn't get it working! I assume you're on windows; the contained exe file should work unless
- you have a 32 bit machine
- you are using gpu when it is not supported (try cpu version first, then enable gpu if that works)
- maybe you need to install the VC++ 2015 redistributable

**Comment by featurecat** [comment]
on windows you probably won't need to compile the next branch since I provided a copy already.

**Comment by WYVYW** [comment]
Works fine out of the box for me on win10. It took maybe a minute or two to download the latest net (I did not count the time).

**Comment by DonMathi** [comment]
It worked fine out of the box on my work computer also, but my home computer must have something missing

**Comment by featurecat** [comment]
I would start with the VC++ 2015 redistributable. see if it helps.

**Comment by DonMathi** [comment]
Works perfectly with with the VC++ 2015 redistributable. Thank you

**Comment by featurecat** [comment]
fantastic! I will definitely add this as an installation instruction for windows. Thank you.

**Comment by DonMathi** [comment]
Thank you for your help. Only: My home computer is about 5-10 slower than my work computer. Can you help with that? 😁

**Comment by DonMathi** [comment]
I think my i7 work computer simply is faster than my older i5 home computer
