### ISSUE TITLE
got the following exception 

### ISSUE THREAD

**Issue by mfkang** [featurecat/lizzie#231]
java -jar "target/lizzie-0.4-shaded.jar"
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at wagner.stephanie.lizzie.gui.Input.keyPressed(Input.java:157)
	at java.awt.Component.processKeyEvent(Component.java:6491)
	at java.awt.Component.processEvent(Component.java:6310)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Window.processEvent(Window.java:2025)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by mfkang** [comment]
environment:

Centos 7.4, aarch64, openjdk 1.8.0_161-b14

**Comment by featurecat** [comment]
try using official oracle jdk. let me know if that fixes it.

**Comment by mfkang** [comment]
unfortunately, on arm64, using oracle jdk @ 
http://download.oracle.com/otn-pub/java/jdk/8u172-b11/a58eab1ec242421181065cdc37240b08/jdk-8u172-linux-arm64-vfp-hflt.tar.gz

will get the error below:
Exception in thread "main" java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at javax.swing.JFrame.<init>(JFrame.java:233)
	at wagner.stephanie.lizzie.gui.LizzieFrame.<init>(LizzieFrame.java:101)
	at wagner.stephanie.lizzie.Lizzie.main(Lizzie.java:43)

I do not where I can find a headless configuration oracle arm64 JDK version.

**Comment by featurecat** [comment]
That's a problem... are you able to run any graphical Java applications on your machine such as KGS?

**Comment by mfkang** [comment]
Sorry for a little bit late respond.

Yes. I can use openjdk to run KGS app.

**Comment by mfkang** [comment]
With Lizzie 0.5 release, I got error below:

$ java -jar "target/lizzie-0.5-shaded.jar"
Leelaz process ended.
java.io.IOException: Broken pipe
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:141)
        at featurecat.lizzie.analysis.Leelaz.sendCommand(Leelaz.java:301)
        at featurecat.lizzie.analysis.Leelaz.ponder(Leelaz.java:360)
        at featurecat.lizzie.analysis.Leelaz.togglePonder(Leelaz.java:366)
        at featurecat.lizzie.Lizzie.lambda$main$0(Lizzie.java:42)
        at java.lang.Thread.run(Thread.java:748)

I built leeza zero CPU only version from source. The leelaz binary and best-network had been copied into lizzie top directory.

**Comment by featurecat** [comment]
that error usually happens if Leelaz was unable to start correctly. try running it via command line with the command in ur Config file, and see if you can get it to start.

**Comment by mfkang** [comment]
Just noticed config file. Leelaz is running after some minor modification in config file.

But some error got later:
Exception in thread "AWT-EventQueue-0" java.lang.ArithmeticException: / by zero
        at featurecat.lizzie.gui.BoardRenderer.convertScreenToCoordinates(BoardRenderer.java:943)
        at featurecat.lizzie.gui.LizzieFrame.onMouseMoved(LizzieFrame.java:816)
        at featurecat.lizzie.gui.Input.mouseMoved(Input.java:59)
        at java.awt.Component.processMouseMotionEvent(Component.java:6578)
        at java.awt.Component.processEvent(Component.java:6302)
        at java.awt.Container.processEvent(Container.java:2237)
        at java.awt.Window.processEvent(Window.java:2025)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2295)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Looks some issue about aarch64 java jdk. I will close this issue now.
