### ISSUE TITLE
"pass" in suggestion?

### ISSUE THREAD

**Issue by kaorahi** [featurecat/lizzie#249]
I experienced the following error on leela-zero/next and lizzie/next.
It seems that we need to check "pass" (or "Pass") in bestMoves at
drawLeelazSuggestions(BoardRenderer.java:462).

    Exception in thread "AWT-EventQueue-0" java.lang.NumberFormatException: For input string: "ass"
            at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
            at java.lang.Integer.parseInt(Integer.java:580)
            at java.lang.Integer.parseInt(Integer.java:615)
            at wagner.stephanie.lizzie.rules.Board.convertNameToCoordinates(Board.java:70)
            at wagner.stephanie.lizzie.gui.BoardRenderer.drawLeelazSuggestions(BoardRenderer.java:462)
            at wagner.stephanie.lizzie.gui.BoardRenderer.draw(BoardRenderer.java:107)
            at wagner.stephanie.lizzie.gui.LizzieFrame.paint(LizzieFrame.java:370)

**Comment by featurecat** [comment]
Ah I can't remember if this was fixed. I hope it was fixed for release... otherwise, at least it's infrequent... :worried:
