### ISSUE TITLE
java.io.IOException: Problem reading font data

### ISSUE THREAD

**Issue by smiley159** [featurecat/lizzie#259]
I got this error when I ran "java -jar lizzie.jar"
Any Idea how I can fix this.

Thx!

**Comment by smiley159** [comment]
To be clear

D:\lizzie-master> java -jar "target/lizzie-0.4-shaded.jar"
Creating config file lizzie.properties
Creating config file persist.properties
Leelaz process ended.
java.io.IOException: Problem reading font data.
        at java.awt.Font.createFont0(Unknown Source)
        at java.awt.Font.createFont(Unknown Source)
        at wagner.stephanie.lizzie.gui.LizzieFrame.<clinit>(LizzieFrame.java:90)
        at wagner.stephanie.lizzie.Lizzie.main(Lizzie.java:43)

**Comment by smiley159** [comment]
[Previous issue](https://github.com/featurecat/lizzie/issues/121)

> You need to download the best-network from zero.sjeng.org/best-network. The result of this is a .gz file. Open it with 7-zip (www.7-zip.org, or an equivalent zipping utility). extract the file, resulting in a .txt file.
> 
> You can: remove the .txt extension. Then rename it to "network"

Yep this is the case for me. Not only to rename the file but also make sure that you remove the .txt extension. If you cannot manage to remove the ".txt" extension then just edit the lizzie.properties and change from "network" to "network.txt"
