### ISSUE TITLE
new to lizzie 0.5, program does not work at all

### ISSUE THREAD

**Issue by DATOUBABA** [featurecat/lizzie#311]
got the following when trying to run lizzie, can anyone please help? appreciate it.

C:\Users\danie\Desktop\Leela\lizzie>java -jar lizzie.jar
Exception in thread "AWT-EventQueue-0" java.lang.ArithmeticException: / by zero
        at featurecat.lizzie.gui.BoardRenderer.convertScreenToCoordinates(BoardRenderer.java:943)
        at featurecat.lizzie.gui.LizzieFrame.onMouseMoved(LizzieFrame.java:816)
        at featurecat.lizzie.gui.Input.mouseMoved(Input.java:59)
        at java.awt.Component.processMouseMotionEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Window.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)Leelaz process ended.

**Comment by featurecat** [comment]
It's odd that we've never seen this issue yet. I'll look into it when I get home to fix it.

**Comment by DATOUBABA** [comment]
thanks very much

**Comment by DATOUBABA** [comment]
Figured it out – VC2015 was missing. Installed VC2015 and lizzie works just fine.

发件人: featurecat
发送时间: 2018年6月26日 8:29
收件人: featurecat/lizzie
抄送: DATOUBABA; Author
主题: Re: [featurecat/lizzie] new to lizzie 0.5, program does not work atall (#311)

It's odd that we've never seen this issue yet. I'll look into it when I get home to fix it.

**Comment by SaiNoKeshin** [comment]
Hi everyone!

I've been reading this topic, it's strange though..
I've got the same error, even though Lizzie works mostly fine (can't get her to play handicapped game).
I've installed VC2015 since 2015, since I frequently use Visual Studio since the 2008 version.
I've checked and it is installed, so what else is there to do to prevent this message?

Thank you for your consideration.

C:\Users\curti\Downloads\Setup\Lizzie\Lizzie.0.5.Windows.x64.GPU\lizzie>java -jar Lizzie.jar
Exception in thread "AWT-EventQueue-0" java.lang.ArithmeticException: / by zero
        at featurecat.lizzie.gui.BoardRenderer.convertScreenToCoordinates(BoardRenderer.java:943)
        at featurecat.lizzie.gui.LizzieFrame.onMouseMoved(LizzieFrame.java:816)
        at featurecat.lizzie.gui.Input.mouseMoved(Input.java:59)
        at java.desktop/java.awt.Component.processMouseMotionEvent(Unknown Source)
        at java.desktop/java.awt.Component.processEvent(Unknown Source)
        at java.desktop/java.awt.Container.processEvent(Unknown Source)
        at java.desktop/java.awt.Window.processEvent(Unknown Source)
        at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.EventQueue.access$600(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

**Comment by featurecat** [comment]
so you're saying lizzie works, but you get this error message?

**Comment by SaiNoKeshin** [comment]
Exactly.

Lizzie works, I can study sgf, or play games against her.
But I still get that error.

**Comment by featurecat** [comment]
then it's ok I guess.... we can fix it later. handicap games are bugged regardless, I'm not sure how that happened >~<

**Comment by gjm11** [comment]
Over in /r/cbaduk there's someone reporting that Lizzie crashes out with this division-by-zero error. I suggested that they try installing the VC++2015 redistributable as per DATOUBABA's comments above, and if I'm understanding them right what now happens is that the CPU-only version of Lizzie works fine while the GPU-enabled one crashes with the division-by-zero error. That doesn't make any sense to me (I'd have thought the CPU/GPU distinction concerns only the Leela Zero engine itself) but maybe someone here has more clue than I have. Here's the Reddit thread: https://www.reddit.com/r/cbaduk/comments/99w0ji/new_computer_lizzie_not_working/
