### ISSUE TITLE
Leela zero is not getting loaded

### ISSUE THREAD

**Issue by someone235** [featurecat/lizzie#328]
When I start lizzie I get the message "Leela zero is loading...", but it doesn't ever get loaded, and I have no error message.
I use Xubuntu 18.04

**Comment by klaas1979** [comment]
I got the same problem using Mac OS X. I have leela-zero build it is working (copied it to lizzie directory as in the readme). I can force play via Enter-key. I edited the config file to get the outputs from leelaz and get stuff like:
```
Klaas-MBP:lizzie0.5 klaas$ java -jar Lizzie.jar 
> 1 version
> 2 lz-analyze 10
=1 0.15
> 3 time_settings 0 2 1
> 4 genmove B
=3 
=4 D4
> 5 time_settings 0 2 1
> 6 genmove W
=5 
=6 Q4
> 7 time_settings 0 2 1
> 8 genmove B
=7 
=8 D16
> 9 time_settings 0 2 1
> 10 genmove W
=9 
=10 Q17
```

But the message "Leela Zero is loading..." never disappears.

I cannot toggle "pondering" via space nor the options f, w, g and v.

**Comment by featurecat** [comment]
Really strange... and the weight file is correct then? I should have a debug Config option. I can send you another version of Lizzie which will output more info. I can do this by tomorrow night I guess. I just got back from England tonight. Let me know if you solve it in the meantime.

**Comment by klaas1979** [comment]
It is very strange, I did not figure it out, so cannot give concrete cause or directions :( I cannot recreate the problem and the solution. What I did:
1) Checkout latest lizzie and build lizzie via maven (mvn package)
2) Clean Checkout of leela-zero with the commit dae7011c1c8b03d4554410230015dde84118a9b7 (latest commit did not work leelaz is crashing)
3) using the provided network from your release package or the newest network with Hash 050375ce
==> it is working

So nothing to do for you but still strange. @someone235 maybe you can try it as stated above.

**Comment by someone235** [comment]
I configured Leela Zero to work with CPU. Can it be related?

**Comment by humuyan** [comment]
same problem +1
However pressing enter to force leela zero move works. No error message.

**Comment by fallcat** [comment]
@humuyan @klaas1979 @someone235  Have you solved the problem? I can't get mine working on Mac and pressing enter to force leela zero works too.

**Comment by someone235** [comment]
No, I didn't solve it

**Comment by OlivierBlanvillain** [comment]
@someone235 Anything showing up in the console?

**Comment by streetplay** [comment]
I'm having the same issue. I did get this exception when it happened if it's of help

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException

at featurecat.lizzie.gui.BoardRenderer.drawLeelazSuggestions(BoardRenderer.java:506)

at featurecat.lizzie.gui.BoardRenderer.draw(BoardRenderer.java:106)

at featurecat.lizzie.gui.LizzieFrame.paint(LizzieFrame.java:373)

at javax.swing.RepaintManager$4.run(Unknown Source)

at javax.swing.RepaintManager$4.run(Unknown Source)

at java.security.AccessController.doPrivileged(Native Method)

at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)

at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)

at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)

at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)

at javax.swing.RepaintManager.access$1200(Unknown Source)

at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)

at java.awt.event.InvocationEvent.dispatch(Unknown Source)

at java.awt.EventQueue.dispatchEventImpl(Unknown Source)

at java.awt.EventQueue.access$500(Unknown Source)

at java.awt.EventQueue$3.run(Unknown Source)

at java.awt.EventQueue$3.run(Unknown Source)

at java.security.AccessController.doPrivileged(Native Method)

at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)

at java.awt.EventQueue.dispatchEvent(Unknown Source)

at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)

at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)

at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)

at java.awt.EventDispatchThread.pumpEvents(Unknown Source)

at java.awt.EventDispatchThread.pumpEvents(Unknown Source)

at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by klaas1979** [comment]
> @humuyan @klaas1979 @someone235 Have you solved the problem? I can't get mine working on Mac and pressing enter to force leela zero works too.

I have a parallels instalation and made it work there.

**Comment by seopsx** [comment]
I also get "Exception in thread "AWT-EventQueue-1" java.lang.NullPointerException" and blank window.
Running Lizzie on Ubuntu 18.04, Maven 3.5.2 and Java 8.
[lizzie_0.6_error.txt](https://github.com/featurecat/lizzie/files/2567737/lizzie_0.6_error.txt)

**Comment by zsalch** [comment]
@someone235 @seopsx 

There is a test version [here](https://github.com/zsalch/lizzie/releases/tag/v0.6%2B).
Maybe you can try it and let me know the result.

**Comment by zsalch** [comment]
@seopsx 
I tried on Ubuntu 18.04 and Jdk1.8.0_191, it seems ok, could you like to share your jkd version.
![image](https://user-images.githubusercontent.com/42595514/48709911-daa3d700-ec41-11e8-8f81-9ea4813501cc.png)

**Comment by seopsx** [comment]
@zsalch 
> There is a test version here.
> Maybe you can try it and let me know the result.
> 

The test version has the same bug.

> I tried on Ubuntu 18.04 and Jdk1.8.0_191, it seems ok, could you like to share your jkd version.

```
$ java -version
 openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-0ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
```

**Comment by someone235** [comment]
Still doesn't work for me, even with the test version

**Comment by zsalch** [comment]
Before fixing this problem, I recommend using Oracle's official Java 1.8 or turning off the show-comment option in the configuration file:
Show-comment: false

Let me know if have any questions.

**Comment by someone235** [comment]
> Before fixing this problem, I recommend using Oracle's official Java 1.8 or turning off the show-comment option in the configuration file:
> Show-comment: false
> 
> Let me know if have any questions.

Now I get

    $ java -jar lizzie-0.6+.jar
    Leelaz process ended.
