### ISSUE TITLE
Getting debug output from lizzie leelaz

### ISSUE THREAD

**Issue by mkmatlock** [featurecat/lizzie#347]
I'm working on getting leelaz to run remotely on AWS. I actually run it inside a docker container running on the aws machine, which may be causing some trouble. Unfortunately, while lizzie appears to connect and startup, it shortly exits.

Enabling print-comms in the config just gives me:
> 1 version
> 2 lz-analyze 10
Leelaz process ended.

Is there any way to get more detailed debugging information from lizzie or leelaz about why the process ended?

**Comment by mkmatlock** [comment]
Ok, I finally figured out to get lizzie to start up, I needed the -i flag with docker without -t to ensure the process was interactive with stdin without incorrectly combining stderr and stdout streams.

What happens now is, Lizzie starts up, and then if I play a move for black, win rates and variations start appearing, but if I play another move, the win rates and variations stop appearing. The board can still be used to play moves and the app still runs, but the following is printed on the command line:

```
> 1 version
> 2 lz-analyze 10
> 3 play B Q4
> 4 lz-analyze 10
=3
=4
> 5 name
=5 Leela Zero
Exception in thread "Thread-2" java.lang.ArrayIndexOutOfBoundsException: 1
	at featurecat.lizzie.analysis.Leelaz.parseLine(Leelaz.java:231)
	at featurecat.lizzie.analysis.Leelaz.read(Leelaz.java:271)
	at featurecat.lizzie.analysis.Leelaz$$Lambda$11/1421676810.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
> 6 lz-analyze 10
> 7 undo
> 8 lz-analyze 10
> 9 play B R4
> 10 lz-analyze 10
> 11 play W D4
> 12 lz-analyze 10
> 13 play B Q17
> 14 lz-analyze 10
> 15 play W D17
> 16 lz-analyze 10
```

**Comment by mkmatlock** [comment]
I got it to work by commenting out the version check at lines 231-234 of the Leelaz parser. Apparently the version number returned is not as expected. Perhaps this is a bug?

**Comment by infinity0** [comment]
@mkmatlock which lines did you comment out? Your issue sounds like the problem I am having in #455

**Comment by infinity0** [comment]
Although I don't get any exception and the leelaz process continues running but at low CPU usage.
