### ISSUE TITLE
Can't start lizzie

### ISSUE THREAD

**Issue by subbbo** [featurecat/lizzie#35]
Windows7 64 cpu version.
When I double click on jar file nothing happens. When running through console I get:
time_left b 0 0
Leelaz process ended.
and nothing happens afterwards

**Comment by featurecat** [comment]
what happens if you run the provided Leelaz file via command line?

**Comment by featurecat** [comment]
(just Leelaz. not lizzie)

**Comment by subbbo** [comment]
How would I do that? I don't have any experience with leela or other bots.

**Comment by featurecat** [comment]
open a command line window in that directory and type Leela.exe -w network

please let me know what the output is!

**Comment by subbbo** [comment]
I don't have Leela.exe in the folder only leelaz.exe. So I did it with leelaz.exe - here's a screenshot of what happened https://i.imgur.com/kDBkDgl.jpg

**Comment by featurecat** [comment]
could you please translate the error to English?

**Comment by subbbo** [comment]
"Error when launching the application (0xc000007b). To exit the application click OK button."

**Comment by featurecat** [comment]
I see... I'll look into this later today to try and fix it. sorry that it is not working yet

**Comment by goplayerjuggler** [comment]
I tried leelaz.exe in the gpu version folder and got:

> ---------------------------
> leelaz.exe - System Error
> ---------------------------
> The program can't start because MSVCP140.dll is missing from your computer. Try reinstalling the program to fix this problem. 
> 

I got the same error when running the cpu version.

**Comment by goplayerjuggler** [comment]
I just got past the error message stage by manually adding MSVCP140.dll and also vcruntime140.dll (I had them on another machine). Now it's running the OpenCL SGEMM tuner - seems promising.

**Comment by featurecat** [comment]
Yay! glad that worked. @subbbo could you try these and see if it fixes anything? I'll include all the dlls in the future

**Comment by subbbo** [comment]
@featurecat I have both those files in system32 folder

**Comment by Flanforever** [comment]
I got the same MSVCP140.dll error when running the CPU only version.

Now it is showing:
time_left b 0 0
Using 2 thread(s).
RNG seed: 15369807786737703591
Using per-move time margin of 0.00s.
Detecting residual layers...v1...128 channels...10 blocks.
BLAS Core: Sandybridge
=

java.lang.NullPointerException
        at wagner.stephanie.lizzie.analysis.Leelaz.parseLine(Leelaz.java:122)
        at wagner.stephanie.lizzie.analysis.Leelaz.read(Leelaz.java:155)
        at java.lang.Thread.run(Unknown Source)

**Comment by bittsitt** [comment]
I got the same error message on my mac. Try removing leelaz_opencl_tuning, that worked for me! Not sure why, but something wrong with the format of the file maybe (I was about to guess line endings, but since Flanforever got the same error on windows, maybe not)? My file attached (had to add .txt to be allowed to upload)
[leelaz_opencl_tuning.txt](https://github.com/featurecat/lizzie/files/1878830/leelaz_opencl_tuning.txt)

Might be a separate bug, but since I found Flanforevers comment, I didnt bother making a new issue.

**Comment by boviz** [comment]
I had the same problem. Copying the two missing dll file into the System32 folder  (msvcpl140.dll, vcruntime140.dll) from another machine has solved it. Thanks.
