### ISSUE TITLE
Leelaz has no permission

### ISSUE THREAD

**Issue by ranamar16** [featurecat/lizzie#370]
I'm trying to run lizzie, the program is going up, but stay with the message leela-zero is loading, when i check the terminal, i can see the "./leelaz" has no permission, how do i solve it?

java.io.IOException: Cannot run program "./leelaz" (in directory "."): error=13, Permission denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at featurecat.lizzie.analysis.Leelaz.<init>(Leelaz.java:96)
	at featurecat.lizzie.Lizzie.lambda$main$0(Lizzie.java:38)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=13, Permission denied
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 3 more

**Comment by Atarust** [comment]
You have linux, right? If you are in the terminal, can you execute leela? What is the output?
$ ./leelaz -w weight.gz

You can simply add all permissions by typing
$ chmod 777 leelaz
