### ISSUE TITLE
Issues launching Lizzie

### ISSUE THREAD

**Issue by Kev511** [featurecat/lizzie#371]
I have issues launching Lizzie on mac (OS X El Capitan 10.11.6).

I installed Lizzie 0.4 following the readme instructions.
- compile Leela zero
- copy executable in Lizzie directory
- download best network

When I try to launch Lizzie, I get the following message:
Exception in thread "main" java.lang.UnsupportedClassVersionError: wagner/stephanie/lizzie/Lizzie : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

I installed the last version of Java but the issue is still here.

Thanks in advance for your help.

**Comment by Kev511** [comment]
I noticed that I had the 0.4 versino of Lizzie. I switched to 0.5 and I cloned Leela Zero following this lin, given in the readme: "git clone -b next https://github.com/gcp/leela-zero"

Now I have errors when compiling Leela Zero. Here is what I get when I try "make":

5 warnings generated.
g++ -flto -g -o leelaz Network.o FullBoard.o KoState.o Training.o TimeControl.o UCTSearch.o GameState.o Leela.o SGFParser.o Timing.o Utils.o FastBoard.o SGFTree.o Zobrist.o FastState.o GTP.o Random.o SMP.o UCTNode.o UCTNodePointer.o UCTNodeRoot.o OpenCL.o OpenCLScheduler.o NNCache.o Tuner.o CPUPipe.o  -framework Accelerate -framework OpenCL -lboost_system -lboost_filesystem -lboost_program_options -lpthread -lz
undef: __ZN7NNCache15MIN_CACHE_COUNTE
Undefined symbols for architecture x86_64:
  "NNCache::MIN_CACHE_COUNT", referenced from:
      Network::initialize(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in lto.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [leelaz] Error 1
make: *** [default] Error 2

**Comment by Kev511** [comment]
It seems there is a bug with my compilation of gcp/leela-zero next branch, [see here.](https://github.com/gcp/leela-zero/issues/1865).

So to sum up:
- Lizzie 0.5 can't run on my computer because I can't compile gcp/leela-zero next branch.
- Lizzie 0.4 can't run on my computer with featurecat/leela-zero. I am able to compile but when launching Lizzie, I directly get a "Leelaz process ended."

Any help would be appreciated.

**Comment by oracle9i88** [comment]
your email, I give you a leelaz
