### ISSUE TITLE
no variation moves show when pondering is on

### ISSUE THREAD

**Issue by philbat** [featurecat/lizzie#396]
Hello,
i have downloaded lizzie for linux and made leelaz from the next branch of leela-zero.
When pondering is on, I can see the proposed moves but the variation (sequence of moves) does not show neither on the main board nor on the small board on the left.
I get this :
 Exception in thread "AWT-EventQueue-0" java.lang.NumberFormatException: For input string: ""

Regards

**Comment by hmxxyy** [comment]
I have got exactly the same error on Mac OS Mojave. Is this related to Java version, I am running

java 11 2018-09-25

Here is the full error:
Exception in thread "AWT-EventQueue-0" java.lang.NumberFormatException: For input string: ""
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:662)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at featurecat.lizzie.rules.Board.convertNameToCoordinates(Board.java:73)
	at featurecat.lizzie.analysis.Branch.<init>(Branch.java:28)
	at featurecat.lizzie.gui.BoardRenderer.drawBranch(BoardRenderer.java:372)
	at featurecat.lizzie.gui.BoardRenderer.draw(BoardRenderer.java:90)
	at featurecat.lizzie.gui.LizzieFrame.paint(LizzieFrame.java:373)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:876)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:848)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:848)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:823)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:772)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1890)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by philbat** [comment]
On the same system (debian testing), building next branch of lizzie, and the same leelaz, everything is ok.

**Comment by hmxxyy** [comment]
tried the same on Mac, works too. Thanks @philbat for the info.
