### ISSUE TITLE
Lizzie fails on start-up.

### ISSUE THREAD

**Issue by astr0labe** [featurecat/lizzie#40]
Hi, I have windows 7, and Java 8 Update 161. When I type `C:\Users\Tom\Lizzie\lizzie>java -jar lizzie.jar`, I get the following response:

```
time_left b 0 0
Using 2 thread(s).
RNG seed: 16978191442050247177
Using per-move time margin of 0.00s.
Detecting residual layers...v1...128 channels...10 blocks.
BLAS Core: Haswell
=

java.lang.NullPointerException
        at wagner.stephanie.lizzie.analysis.Leelaz.parseLine(Leelaz.java:122)
        at wagner.stephanie.lizzie.analysis.Leelaz.read(Leelaz.java:155)
        at java.lang.Thread.run(Unknown Source)
```

But when I type `C:\Users\Tom\Lizzie\lizzie>Leelaz.exe -w network`, I get

```
Using 8 thread(s).
RNG seed: 7445661829116835432
Leela Zero 0.13  Copyright (C) 2017-2018  Gian-Carlo Pascutto and contributors
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see the COPYING file for details.

Detecting residual layers...v1...128 channels...10 blocks.
BLAS Core: Haswell

Passes: 0            Black (X) Prisoners: 0
Black (X) to move    White (O) Prisoners: 0

   a b c d e f g h j k l m n o p q r s t
19 . . . . . . . . . . . . . . . . . . . 19
18 . . . . . . . . . . . . . . . . . . . 18
17 . . . . . . . . . . . . . . . . . . . 17
16 . . . + . . . . . + . . . . . + . . . 16
15 . . . . . . . . . . . . . . . . . . . 15
14 . . . . . . . . . . . . . . . . . . . 14
13 . . . . . . . . . . . . . . . . . . . 13
12 . . . . . . . . . . . . . . . . . . . 12
11 . . . . . . . . . . . . . . . . . . . 11
10 . . . + . . . . . + . . . . . + . . . 10
 9 . . . . . . . . . . . . . . . . . . .  9
 8 . . . . . . . . . . . . . . . . . . .  8
 7 . . . . . . . . . . . . . . . . . . .  7
 6 . . . . . . . . . . . . . . . . . . .  6
 5 . . . . . . . . . . . . . . . . . . .  5
 4 . . . + . . . . . + . . . . . + . . .  4
 3 . . . . . . . . . . . . . . . . . . .  3
 2 . . . . . . . . . . . . . . . . . . .  2
 1 . . . . . . . . . . . . . . . . . . .  1
   a b c d e f g h j k l m n o p q r s t

Hash: 9A930BE1616C538E Ko-Hash: A14C933E7669946D

Black time: 01:00:00
White time: 01:00:00

Leela:
```

Can anyone help? Thanks.

**Comment by dfannius** [comment]
This looks like issue #36 - see if the updated release mentioned there works for you.

**Comment by astr0labe** [comment]
Thanks. That fixed it. Sorry for not checking the closed issues.
