### ISSUE TITLE
0.6 UI becomes completely unresponsive

### ISSUE THREAD

**Issue by stridervc** [featurecat/lizzie#448]
I've just install Lizzie 0.6 on my Linux desktop. I was previously running Lizzie 0.5 fine. I've also updated my leela-zero to the latest. Lizzie starts up and seems ok, but pretty soon, like when after loading an sgf, the UI becomes unresponsive and the following message repeats on the console:

Exception in thread "AWT-EventQueue-1" java.lang.NullPointerException
	at java.awt.Component.getLocationOnScreen_NoTreeLock(Component.java:2051)
	at java.awt.Component.getLocationOnScreen(Component.java:2036)
	at java.awt.Component$AccessibleAWTComponent.getLocationOnScreen(Component.java:9489)
	at javax.swing.JComponent$AccessibleJComponent.getLocationOnScreen(JComponent.java:3663)
	at javax.swing.text.JTextComponent$AccessibleJTextComponent.caretUpdate(JTextComponent.java:2559)
	at javax.swing.text.JTextComponent.fireCaretUpdate(JTextComponent.java:397)
	at javax.swing.text.JTextComponent$MutableCaretEvent.fire(JTextComponent.java:4394)
	at javax.swing.text.JTextComponent$MutableCaretEvent.stateChanged(JTextComponent.java:4416)
	at javax.swing.text.DefaultCaret.fireStateChanged(DefaultCaret.java:802)
	at javax.swing.text.DefaultCaret.changeCaretPosition(DefaultCaret.java:1274)
	at javax.swing.text.DefaultCaret.handleSetDot(DefaultCaret.java:1173)
	at javax.swing.text.DefaultCaret.setDot(DefaultCaret.java:1154)
	at javax.swing.text.DefaultCaret$Handler.removeUpdate(DefaultCaret.java:1797)
	at javax.swing.text.AbstractDocument.fireRemoveUpdate(AbstractDocument.java:259)
	at javax.swing.text.AbstractDocument.handleRemove(AbstractDocument.java:622)
	at javax.swing.text.AbstractDocument.remove(AbstractDocument.java:590)
	at javax.swing.JEditorPane.setText(JEditorPane.java:1410)
	at featurecat.lizzie.gui.LizzieFrame.drawComment(LizzieFrame.java:1395)
	at featurecat.lizzie.gui.LizzieFrame.paint(LizzieFrame.java:684)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:842)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.GNOME.Accessibility.AtkWrapper$5.dispatchEvent(AtkWrapper.java:700)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by zsalch** [comment]
Yes, the issue is resolving.

**Comment by stridervc** [comment]
> Yes, the issue is resolving.

Hi. Does this mean you're aware of the issue and devs are working on it, or I should leave it running and it'll resolve itself?

**Comment by OlivierBlanvillain** [comment]
@stridervc The former

**Comment by zsalch** [comment]
@stridervc 
Could you like to share your system and jdk version?

**Comment by stridervc** [comment]
Hi,

I'm running Debian.

$ java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-1~deb9u1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
