### ISSUE TITLE
Am I confused or are the messages confusing?

### ISSUE THREAD

**Issue by ericosman** [featurecat/lizzie#465]
I have questions about these parts (emphasized with red ovals) that appear:
![image](https://user-images.githubusercontent.com/40031348/50167639-9b57bd00-02b7-11e9-9b85-f2b68ae74c45.png)
![image](https://user-images.githubusercontent.com/40031348/50167654-a4488e80-02b7-11e9-854a-5edc8f23d1f3.png)
The questions:
1) When it says "may take awhile", does that mean when it's done, the "is loading" phrase will automatically disappear?
2) I'm on windows 10 on a fairly new hp laptop.  About how long is "may take awhile"?  5 min?  1 hour?  a day?
3) When it says "When Leela Zero finishes setting up, the board will display Leelaz's analysis", analysis of what?    The board shows no stones on it yet.
4) If the answer to number 2 is longer than I'm willing to wait, can I somehow shut down in a way that doesn't lose what's been done so far, so that when I restart lizzie, it will continue setting up?

**Comment by featurecat** [comment]
Hi Eric, we met at the go tournament :) 

1. It really shouldn't take more than 1-2 minutes max. I should have added that to the Readme. 

2. Lizzie has pretty poor error handling. (I'm sorry!). Sometimes Leela zero isn't configured correctly and it "loads" forever. The most common issue is an incorrectly named network file, or something to do with C++ libraries. Try running Leela zero with the command in config.txt, via command line. Reply to this thread with the result - error message or success. You may also want to try installing the Visual C++ 2015 Redistributable from Microsoft.

3. If it was working, you'd be able to see: Leela Zero offers it's suggestions for the first move (4-4, 4-3, etc.)

4. N/A, it's loading forever... 

I'll do my best to help, so please let me know how #2 goes.

**Comment by ericosman** [comment]
wow Annie I didn't know it is you that is behind Lizzie.  Nice!

Anway, I just ran lizzie again from the command line, and it still says "loading" after 10 minutes, and there's no error messages.  Here's a snapshot:

![image](https://user-images.githubusercontent.com/40031348/50178558-e501d100-02d2-11e9-941f-e71bb97f5a1a.png)

**Comment by featurecat** [comment]
Try running this from the terminal:
`.\leelaz.exe --gtp --lagbuffer 0 --weights network.gz`

**Comment by ericosman** [comment]
The leelaz.exe is in a subfolder of the folder that contains network.gz, so if I cd to the subfolder containing leelaz.exe in order to do the command you show above, it gets an error saying network.gz is not found.

As shown in the typescript below, if I copy the network.gz file from the parent folder into the one containing leelaz.exe, then your command seems to do stuff that may be normal.  Please see the typescript below.

Am I on the right track?

What do you think happened?  Did I originally leave out some step?  Or is the documentation missing a step?

I will go back and try lizze.jar again now that I've copied that network.gz file into the subfolder to see whether I have more success.

Here's the typescript that shows that running leelaz.exe from its folder initially fails because it can't find network.gz, but after I copy network.gz from the superfolder, the leelaz.exe seems to be more happy:

Your environment has been set up for using Node.js 8.11.4 (x64) and npm.

C:\Users\Eric>cd C:\Users\Eric\Desktop\folders\apps\lizzie\Lizzie.0.6.Windows.x64.GPU\Lizzie\leela-zero

C:\Users\Eric\Desktop\folders\apps\lizzie\Lizzie.0.6.Windows.x64.GPU\Lizzie\leela-zero>.\leelaz.exe --gtp --lagbuffer 0 --weights network.gz
Using 2 thread(s).
RNG seed: 17737818850137389051
Using per-move time margin of 0.00s.
BLAS Core: Haswell
Could not open weights file: network.gz

C:\Users\Eric\Desktop\folders\apps\lizzie\Lizzie.0.6.Windows.x64.GPU\Lizzie\leela-zero>cd ..

C:\Users\Eric\Desktop\folders\apps\lizzie\Lizzie.0.6.Windows.x64.GPU\Lizzie>.\leelaz.exe --gtp --lagbuffer 0 --weights network.gz
'.\leelaz.exe' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Eric\Desktop\folders\apps\lizzie\Lizzie.0.6.Windows.x64.GPU\Lizzie>cd C:\Users\Eric\Desktop\folders\apps\lizzie\Lizzie.0.6.Windows.x64.GPU\Lizzie\leela-zero

C:\Users\Eric\Desktop\folders\apps\lizzie\Lizzie.0.6.Windows.x64.GPU\Lizzie\leela-zero>cp ..\network.gz .
'cp' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Eric\Desktop\folders\apps\lizzie\Lizzie.0.6.Windows.x64.GPU\Lizzie\leela-zero>copy ..\network.gz .
        1 file(s) copied.

C:\Users\Eric\Desktop\folders\apps\lizzie\Lizzie.0.6.Windows.x64.GPU\Lizzie\leela-zero>.\leelaz.exe --gtp --lagbuffer 0 --weights network.gz
Using 2 thread(s).
RNG seed: 14067868706740931932
Using per-move time margin of 0.00s.
BLAS Core: Haswell
Detecting residual layers...v1...192 channels...15 blocks.
Initializing OpenCL (autodetecting precision).
Detected 1 OpenCL platforms.
Platform version: OpenCL 2.1
Platform profile: FULL_PROFILE
Platform name:    Intel(R) OpenCL
Platform vendor:  Intel(R) Corporation
Device ID:     0
Device name:   Intel(R) HD Graphics 620
Device type:   GPU
Device vendor: Intel(R) Corporation
Device driver: 23.20.16.4973
Device speed:  1050 MHz
Device cores:  24 CU
Device score:  621
Device ID:     1
Device name:   Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
Device type:   CPU
Device vendor: Intel(R) Corporation
Device driver: 7.6.0.611
Device speed:  2700 MHz
Device cores:  4 CU
Device score:  521
Selected platform: Intel(R) OpenCL
Selected device: Intel(R) HD Graphics 620
with OpenCL 2.1 capability.
Half precision compute support: Yes.
OpenCL: using fp16/half compute support.

Started OpenCL SGEMM tuner.
Will try 290 valid configurations.
(1/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 1.4236 ms (46.6 GFLOPS)
(3/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 1.3586 ms (48.8 GFLOPS)
(5/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.8846 ms (75.0 GFLOPS)
(6/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.8360 ms (79.4 GFLOPS)

**Comment by featurecat** [comment]
Sorry, you're right - I was basing my advice on my own Lizzie directory and forgot that I made the default be like your setup. From Lizzie's directory, run
`./leela-zero/leelaz.exe --gtp --lagbuffer 0 --weights network.gz`

Let it run to completion (finishes printing out (1/290, 2/290, etc)). Then let me know what happens - also try running Lizzie at that point and, if it still doesn't work, also upload your Config.txt here.

**Comment by ericosman** [comment]
ok I've started it.

But for the record, since this is windows 10, I had to change your slashes to backslashes.  Here's the command I used:

.\leela-zero\leelaz.exe --gtp --lagbuffer 0 --weights network.gz

**Comment by featurecat** [comment]
oh really!! I didn't realize that would be problematic. It didn't come up when I tested it on windows. So it works when you use \? Could you please verify that it doesn't work when you only change /? Then I can try fixing.

**Comment by ericosman** [comment]
I'm not saying anything necessarily works yet.  But trivially, here's what happens if I use the slashes instead of backslashes:

C:\Users\Eric\Desktop\folders\apps\lizzie\Lizzie.0.6.Windows.x64.GPU\Lizzie>./leela-zero/leelaz.exe --gtp --lagbuffer 0 --weights network.gz
'.' is not recognized as an internal or external command,
operable program or batch file.

**Comment by ericosman** [comment]
I'm not sure how long you wanted me to wait.  It's been going about 40 minutes now, and here's the typescript.   It's still running.  What do you suggest next?

I see by looking at the end of the typescript that we're up to 6 out of 290.   It took 2/3 of an hour for that much, so if it's linear, we're talking 290/6*2/3 hours so it will be about 38 hours.  

The typescript so far:

C:\Users\Eric\Desktop\folders\apps\lizzie\Lizzie.0.6.Windows.x64.GPU\Lizzie>.\leela-zero\leelaz.exe --gtp --lagbuffer 0 --weights network.gz
Using 2 thread(s).
RNG seed: 3305388503231536993
Using per-move time margin of 0.00s.
BLAS Core: Haswell
Detecting residual layers...v1...192 channels...15 blocks.
Initializing OpenCL (autodetecting precision).
Detected 1 OpenCL platforms.
Platform version: OpenCL 2.1
Platform profile: FULL_PROFILE
Platform name:    Intel(R) OpenCL
Platform vendor:  Intel(R) Corporation
Device ID:     0
Device name:   Intel(R) HD Graphics 620
Device type:   GPU
Device vendor: Intel(R) Corporation
Device driver: 23.20.16.4973
Device speed:  1050 MHz
Device cores:  24 CU
Device score:  621
Device ID:     1
Device name:   Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
Device type:   CPU
Device vendor: Intel(R) Corporation
Device driver: 7.6.0.611
Device speed:  2700 MHz
Device cores:  4 CU
Device score:  521
Selected platform: Intel(R) OpenCL
Selected device: Intel(R) HD Graphics 620
with OpenCL 2.1 capability.
Half precision compute support: Yes.
OpenCL: using fp16/half compute support.

Started OpenCL SGEMM tuner.
Will try 290 valid configurations.
(1/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.8367 ms (79.3 GFLOPS)
(3/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.7680 ms (86.4 GFLOPS)
(5/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.5001 ms (132.7 GFLOPS)
(6/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.4921 ms (134.8 GFLOPS)

**Comment by ericosman** [comment]
Hmmm.   We're at an hour now, and for at least 20 minutes no more lines have shown up beyond the 6/290 one.  Task manager shows it as still compute-bound.  Is this normal?  If not, is it a clue?

**Comment by alreadydone** [comment]
If 6/290 takes 40 minutes to appear, then completing the tuning will indeed require 38 hours.
I've never heard of a tuning run taking so long, but maybe it's just that the integrated GPU is too slow; in that case using the cpuonly versions from https://github.com/gcp/leela-zero/releases/tag/v0.16 might actually be faster.

**Comment by ericosman** [comment]
still hasn't printed anything beyond the 6/290 line, although task manager says it's still computing.  So I don't have any faith in any extrapolation of completion time, given that those first 6 lines came out relatively quickly and then nada after that.

**Comment by alreadydone** [comment]
Can you see whether the file leelaz_opencl_tuning has any content? If it has, maybe run the same command in another window (I think this time tuning will be skipped and you'll see something different)?

**Comment by ericosman** [comment]
I don't see any such file

**Comment by alreadydone** [comment]
Output shows
> Selected device: Intel(R) HD Graphics 620

**Comment by featurecat** [comment]
yes definitely give cpu mode a try

**Comment by ericosman** [comment]
I wasn't exactly sure what you're asking me to do, so I did the following, hoping it is what you meant:

1) In my local machine lizzie folder, I made a copy of the Lizzie.0.6.Windows.x64.GPU folder and renamed it to Lizzie.0.6.Windows.x64.CPU64.
2) In the new folder, I replaced the leela-zero subfolder with the leela-zero subfolder I downloaded from https://github.com/gcp/leela-zero/releases/tag/v0.16.  On that page, I chose https://github.com/gcp/leela-zero/releases/download/v0.16/leela-zero-0.16-cpuonly-win64.zip.
3) I then cd'd on my local machine to lizzie\Lizzie.0.6.Windows.x64.CPU64\Lizzie and gave the same command as before, namely .\leela-zero\leelaz.exe --gtp --lagbuffer 0 --weights network.gz.

It's been running for about 8 minutes.  It fairly quickly spewed the typescript shown below, and then it's just sitting there silent for most of that 8 minutes:

PERHAPS SIGNIFICANT:  I just looked at task manager, and although my DOS window shows the typescript shown belo, the task manager is NOT showing the application using ANY of the cpu.  So maybe it is waiting for something else?

C:\Users\Eric>cd C:\Users\Eric\Desktop\folders\apps\lizzie\Lizzie.0.6.Windows.x64.CPU64\Lizzie

C:\Users\Eric\Desktop\folders\apps\lizzie\Lizzie.0.6.Windows.x64.CPU64\Lizzie>.\leela-zero\leelaz.exe --gtp --lagbuffer 0 --weights network.gz
Using 4 thread(s).
RNG seed: 10645007962565245562
Using per-move time margin of 0.00s.
BLAS Core: Haswell
Detecting residual layers...v1...192 channels...15 blocks.
Initializing CPU-only evaluation.
Setting max tree size to 4324 MiB and cache size to 480 MiB.

**Comment by alreadydone** [comment]
The CPU version did progress further by displaying memory setting info. If you start lizzie in Lizzie.0.6.Windows.x64.CPU64\Lizzie, does it work now?

**Comment by ericosman** [comment]
I think it does!   It's showing something I've NEVER seen before.  All I used to see is the picture shown at the very top of this thread.    Now it's showing a whole bunch of colors and flashing numbers, which I'll have to look around in the documentation to see if it is explained.

There's an NPE shown on the console.

Here's the NPE and then an image of what the screen look like:

Your environment has been set up for using Node.js 8.11.4 (x64) and npm.

C:\Users\Eric>cd C:\Users\Eric\Desktop\folders\apps\lizzie\Lizzie.0.6.Windows.x64.CPU64\Lizzie

C:\Users\Eric\Desktop\folders\apps\lizzie\Lizzie.0.6.Windows.x64.CPU64\Lizzie>java -jar Lizzie.jar
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at featurecat.lizzie.gui.BoardRenderer.drawBranch(BoardRenderer.java:369)
        at featurecat.lizzie.gui.BoardRenderer.draw(BoardRenderer.java:101)
        at featurecat.lizzie.gui.LizzieFrame.paint(LizzieFrame.java:646)
        at java.desktop/javax.swing.RepaintManager$4.run(Unknown Source)
        at java.desktop/javax.swing.RepaintManager$4.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
        at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
        at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
        at java.desktop/javax.swing.RepaintManager.access$1200(Unknown Source)
        at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.EventQueue.access$600(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

![image](https://user-images.githubusercontent.com/40031348/50310747-f680df80-0470-11e9-9244-75331a56eeea.png)

**Comment by featurecat** [comment]
Looks maybe working? Try Lizzie.

**Comment by featurecat** [comment]
The exception might be ok so long as it didn't actually crash or stop working. Try using the interface?

**Comment by zsalch** [comment]
@ericosman @featurecat 
About 2:

A new PR @459 will open the config dialog when the lizzie config with errors.
and provides a simple wizard by '...' button in the config dialog.

**Comment by alreadydone** [comment]
No matter what the GPU is, the tuning run shouldn't consume infinite time ... Since the first 6 tuning configs completed relatively quickly, it's even more mysterious (only some of the configs are extremely slow?).
Maybe @ericosman can test the GPU version for a few more times in command line and report in gcp/leela-zero issues if the problem persists.

**Comment by alreadydone** [comment]
Since you copied the whole Lizzie folder, I think you just need to navigate to the original LizzieGPU folder and run the command
.\leela-zero\leelaz.exe --gtp --lagbuffer 0 --weights network.gz
(I suggest that --gtp be taken off)
I think running several times (opening another console when one hangs) and each time recording the config it stucks on (are they similar in some aspects?) would be helpful.

**Comment by ericosman** [comment]
As shown in the windows 10 CMD typescript below, the failure is consistent.    I'm using

.\leela-zero\leelaz.exe --lagbuffer 0 --weights network.gz

and it always quickly announces 6 out of 290 configurations and then announces nothing after that.

Here's something though that might be a clue.  If I press CTRL-C fairly quickly after it gets to configuration 6, I can interrupt it.  But if I wait another minute or so, then I can no longer interrupt with CTRL-C and I have to "X" out the entire CMD window to get rid of it.

The typescript:


Microsoft Windows [Version 10.0.17134.472]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Program Files\nodejs>.\leela-zero\leelaz.exe --gtp --lagbuffer 0 --weights network.gz

C:\Program Files\nodejs>cd C:\Users\Eric\Desktop\folders\apps\lizzie\Lizzie.0.6.Windows.x64.GPU\Lizzie

C:\Users\Eric\Desktop\folders\apps\lizzie\Lizzie.0.6.Windows.x64.GPU\Lizzie>.\leela-zero\leelaz.exe --gtp --lagbuffer 0 --weights network.gz
Using 2 thread(s).
RNG seed: 17634407051344554346
Using per-move time margin of 0.00s.
BLAS Core: Haswell
Detecting residual layers...v1...192 channels...15 blocks.
Initializing OpenCL (autodetecting precision).
Detected 1 OpenCL platforms.
Platform version: OpenCL 2.1
Platform profile: FULL_PROFILE
Platform name:    Intel(R) OpenCL
Platform vendor:  Intel(R) Corporation
Device ID:     0
Device name:   Intel(R) HD Graphics 620
Device type:   GPU
Device vendor: Intel(R) Corporation
Device driver: 23.20.16.4973
Device speed:  1050 MHz
Device cores:  24 CU
Device score:  621
Device ID:     1
Device name:   Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
Device type:   CPU
Device vendor: Intel(R) Corporation
Device driver: 7.6.0.611
Device speed:  2700 MHz
Device cores:  4 CU
Device score:  521
Selected platform: Intel(R) OpenCL
Selected device: Intel(R) HD Graphics 620
with OpenCL 2.1 capability.
Half precision compute support: Yes.
OpenCL: using fp16/half compute support.

Started OpenCL SGEMM tuner.
Will try 290 valid configurations.
(1/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.8519 ms (77.9 GFLOPS)
(3/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.7742 ms (85.7 GFLOPS)
(5/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.4924 ms (134.8 GFLOPS)
(6/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.4673 ms (142.0 GFLOPS)
^C
C:\Users\Eric\Desktop\folders\apps\lizzie\Lizzie.0.6.Windows.x64.GPU\Lizzie>.\leela-zero\leelaz.exe --gtp --lagbuffer 0 --weights network.gz
Using 2 thread(s).
RNG seed: 14159037968197606561
Using per-move time margin of 0.00s.
BLAS Core: Haswell
Detecting residual layers...v1...192 channels...15 blocks.
Initializing OpenCL (autodetecting precision).
Detected 1 OpenCL platforms.
Platform version: OpenCL 2.1
Platform profile: FULL_PROFILE
Platform name:    Intel(R) OpenCL
Platform vendor:  Intel(R) Corporation
Device ID:     0
Device name:   Intel(R) HD Graphics 620
Device type:   GPU
Device vendor: Intel(R) Corporation
Device driver: 23.20.16.4973
Device speed:  1050 MHz
Device cores:  24 CU
Device score:  621
Device ID:     1
Device name:   Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
Device type:   CPU
Device vendor: Intel(R) Corporation
Device driver: 7.6.0.611
Device speed:  2700 MHz
Device cores:  4 CU
Device score:  521
Selected platform: Intel(R) OpenCL
Selected device: Intel(R) HD Graphics 620
with OpenCL 2.1 capability.
Half precision compute support: Yes.
OpenCL: using fp16/half compute support.

Started OpenCL SGEMM tuner.
Will try 290 valid configurations.
(1/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.8907 ms (74.5 GFLOPS)
(3/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.7644 ms (86.8 GFLOPS)
(5/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.4853 ms (136.7 GFLOPS)
(6/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.4707 ms (141.0 GFLOPS)
^C
C:\Users\Eric\Desktop\folders\apps\lizzie\Lizzie.0.6.Windows.x64.GPU\Lizzie>.\leela-zero\leelaz.exe --lagbuffer 0 --weights network.gz
Using 2 thread(s).
RNG seed: 2790059249765459181
Using per-move time margin of 0.00s.
Leela Zero 0.16  Copyright (C) 2017-2018  Gian-Carlo Pascutto and contributors
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see the COPYING file for details.

BLAS Core: Haswell
Detecting residual layers...v1...192 channels...15 blocks.
Initializing OpenCL (autodetecting precision).
Detected 1 OpenCL platforms.
Platform version: OpenCL 2.1
Platform profile: FULL_PROFILE
Platform name:    Intel(R) OpenCL
Platform vendor:  Intel(R) Corporation
Device ID:     0
Device name:   Intel(R) HD Graphics 620
Device type:   GPU
Device vendor: Intel(R) Corporation
Device driver: 23.20.16.4973
Device speed:  1050 MHz
Device cores:  24 CU
Device score:  621
Device ID:     1
Device name:   Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
Device type:   CPU
Device vendor: Intel(R) Corporation
Device driver: 7.6.0.611
Device speed:  2700 MHz
Device cores:  4 CU
Device score:  521
Selected platform: Intel(R) OpenCL
Selected device: Intel(R) HD Graphics 620
with OpenCL 2.1 capability.
Half precision compute support: Yes.
OpenCL: using fp16/half compute support.

Started OpenCL SGEMM tuner.
Will try 290 valid configurations.
(1/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.8846 ms (75.0 GFLOPS)
(3/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.7777 ms (85.3 GFLOPS)
(5/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.4830 ms (137.4 GFLOPS)
(6/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.4734 ms (140.2 GFLOPS)

**Comment by alreadydone** [comment]
Thanks for the tests. Filed https://github.com/gcp/leela-zero/issues/2090.
