### ISSUE TITLE
not work in fedora 29

### ISSUE THREAD

**Issue by hermithuang** [featurecat/lizzie#478]
```
java -jar lizzie.jar 
Creating config file config.txt
Creating config file persist
Exception in thread "main" java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at javax.swing.JFrame.<init>(JFrame.java:233)
	at featurecat.lizzie.gui.LizzieFrame.<init>(LizzieFrame.java:137)
	at featurecat.lizzie.Lizzie.main(Lizzie.java:27)
```
```
$java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

$uname
4.19.13-300.fc29.x86_64 #1 SMP Sat Dec 29 22:54:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Typo-0** [comment]
It's working for me with Fedora 29 with the same issues 

    $java -version
    openjdk version "1.8.0_191"
    OpenJDK Runtime Environment (build 1.8.0_191-b12)
    OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

    $uname -a
    4.19.13-300.fc29.x86_64 #1 SMP Sat Dec 29 22:54:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
