### ISSUE TITLE
It hangs on startup with the "loading" status and some white box hanging on top of the window

### ISSUE THREAD

**Issue by yurivict** [featurecat/lizzie#540]
![lizzie-Screenshot_2019-06-09_16-04-11](https://user-images.githubusercontent.com/271906/59165452-99d1b980-8ad0-11e9-89cb-be8825993277.png)

Version 0.6-105-gd0e7040
openjdk8-8.212.4.1
FreeBSD 12 amd64

**Comment by yurivict** [comment]
It also prints:
```
en
java.io.IOException: Broken pipe
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:141)
	at featurecat.lizzie.analysis.Leelaz.sendCommandToLeelaz(Leelaz.java:424)
	at featurecat.lizzie.analysis.Leelaz.trySendCommandFromQueue(Leelaz.java:405)
	at featurecat.lizzie.analysis.Leelaz.sendCommand(Leelaz.java:387)
	at featurecat.lizzie.analysis.Leelaz.startEngine(Leelaz.java:166)
	at featurecat.lizzie.analysis.Leelaz.<init>(Leelaz.java:111)
	at featurecat.lizzie.Lizzie.main(Lizzie.java:33)
Leelaz process ended.
```

Is this normal?
What is wrong?

**Comment by ysangkok** [comment]
I have the same problem on Ubuntu with Leela Zero and `-DUSE_CPU_ONLY=1`. `leelaz` seems to work since I get the prompt if I start it. I am using the human training data.
