### ISSUE TITLE
Almost have Lizzie connected to Leela running in gCloud in windows

### ISSUE THREAD

**Issue by ernop** [featurecat/lizzie#611]
1. I have leelaz running over gcloud and it works when I run it locally with this command:
`gcloud compute ssh "leelazero-v100" --zone "europe-west4-a" --command/leela/leelaz -g -w /leela/best-network.gz -b 0 -t 16 -l leela.log"`

Note: when I run this command from WSL (windows subsystem linux), the connection stays open and I can interact with leela, issuing `name`, `version` commands and playing

But when I run the gcloud command from a cmd window, after initialization the connection breaks.  This is probably the core part of the problem.

See image:
![image](https://user-images.githubusercontent.com/1008221/64068478-7e68dd00-cbed-11e9-99a5-83658eec63ba.png)

2. I'm running lizzie 0.6.  In my config I have an engine running a bat file, like this:
`"engine-command": "remote-leelaz.bat",`
And this file has these contents:
`gcloud compute ssh "leelazero-v100" --zone "europe-west4-a" --command "/leela/leelaz -g -w /leela/best-network.gz -b 0 -t 16 -l leela.log"`

3. My setup: win10.  When I run lizzie with `java -jar lizzie-0.6-shaded.jar` the UI pops up loading engine, but the engine never finishes loading. See image:
![image](https://user-images.githubusercontent.com/1008221/64068464-59746a00-cbed-11e9-84d8-df19e630cc62.png)

4. It looks to me like lizzie is running the bat file, but the connection is breaking immediately.

When I click, the cmd window shows "IOException: The pipe is being closed".  This probably probably means the connection opened by the bat file has already been closed.

`D:\proj\lizzie\lizzie>java -jar lizzie-0.6-shaded.jar
en
> 1 name
> 2 version
> 3 boardsize 19
> 4 komi 7.5
? unknown command
> 5 play B P14
java.io.IOException: The pipe is being closed
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(Unknown Source)
...`

So, questions - how to set up leela to not break the connection when connecting from a cmd window? Or (more difficult), how to run WSL's java to create a normal windows UI, so presumably the linux version of lizzie would be able to keep the gtp connection open?

**Comment by ernop** [comment]
Yes, the problem was not being able to run the ssh command to set up the gtp server from `cmd`.  The solution:
1. install openSSH
2. copy c:\windows\system32\openssh\ssh.exe to the folder you are running the jar from (because lizzie apparently doesn't accept full paths, nor use windows system path to find it)
3. verify you can run this: `ssh.exe -i PKPATH 34.90.54.230 /leela/leelaz -g -w /leela/best-network.gz -b 0 -t 16 -l leela.log`
4. put that command in a batfile and set that batfile as the engine-path

**Comment by ernop** [comment]
Yes, the problem was not being able to run the ssh command to set up the gtp server from `cmd`.  The solution:
1. install openSSH
2. copy c:\windows\system32\openssh\ssh.exe to the folder you are running the jar from (because lizzie apparently doesn't accept full paths, nor use windows system path to find it)
3. verify you can run this: `ssh.exe -i PKPATH 34.90.54.230 /leela/leelaz -g -w /leela/best-network.gz -b 0 -t 16 -l leela.log`
4. put that command in a batfile and set that batfile as the engine-path
