### ISSUE TITLE
Feature request: option to launch without preloading an engine

### ISSUE THREAD

**Issue by hanysz** [featurecat/lizzie#646]
The engine settings dialog box gives a "preload" checkbox for engines 1 through 9, but the box for the default engine is greyed out: currently you *must* load an engine on startup.  (I've tried manually editing the config file to put "" as the default engine.  This just causes Lizzie to hang.)

Sometimes I just want to view an SGF file and don't want to wait for the ten or twenty seconds it takes for the engine to wake up.  At the moment this means I'm using different software for viewing and for analysis, which feels like overkill.

**Comment by featurecat** [comment]
good point... let me see if i can add this now

**Comment by featurecat** [comment]
Here's a compiled version, I just checked in something that does what you wanted. Let me know if you find any bugs.
[lizzie-empty-quotes-no-engine.zip](https://github.com/featurecat/lizzie/files/3774487/lizzie-empty-quotes-no-engine.zip)

**Comment by featurecat** [comment]
Just set the default engine to empty quotes "".

**Comment by hanysz** [comment]
Wow, that was quick, thanks!  I'll try it out later tonight and let you know how it goes.

**Comment by hanysz** [comment]
Sorry, not quite working for me at the moment.  It starts up OK and I can load SGF files, but when I try to start an engine, in the UI I just see "Engine is loading...", and in the terminal it prints an error message that looks like:
```
java.io.IOException: Stream closed
        at java.base/java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:442)
        at java.base/java.io.OutputStream.write(OutputStream.java:113)
        at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
        at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
        at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:143)
        at featurecat.lizzie.analysis.Leelaz.sendCommandToLeelaz(Leelaz.java:527)
        at featurecat.lizzie.analysis.Leelaz.trySendCommandFromQueue(Leelaz.java:506)
        at featurecat.lizzie.analysis.Leelaz.sendCommand(Leelaz.java:480)
        at featurecat.lizzie.analysis.Leelaz.startEngine(Leelaz.java:184)
  *** another 192 lines, tell me if you want to see the whole lot ***
Engine process ended.
```
This is with the same config file that works for the Lizzie 0.7 release.

FYI, I'm running on Ubuntu 18.04, Java build build 10.0.2+13.  Also, it's pretty easy for me to download the source and build it locally if that helps with testing.

Sorry to be a pain, I did hope that this would be relatively easy!
