### ISSUE TITLE
Crash on Windows 10

### ISSUE THREAD

**Issue by MortimerMcMire315** [featurecat/lizzie#657]
Hi there,

I'm using Lizzie 0.7 GPU. When I start up the program by double-clicking on the jar file, I see a command prompt window that exits immediately. When I start up the program from the command line, I see the configuration dialog box, but as soon as I click "OK", the program exits and I see the following stack trace:

```
en
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at featurecat.lizzie.gui.ConfigDialog.applyChange(ConfigDialog.java:1919)
        at featurecat.lizzie.gui.ConfigDialog.access$100(ConfigDialog.java:102)
        at featurecat.lizzie.gui.ConfigDialog$1.actionPerformed(ConfigDialog.java:237)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.WaitDispatchSupport$2.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by featurecat** [comment]
Ah, sorry that this box is not user friendly. it's trying to tell you that no engine is configured... Did you download the release for windows, or compiled it yourself?

**Comment by MortimerMcMire315** [comment]
I downloaded the release for Windows. It looks like the default Engine command uses relative paths (relative to the current working directory, i guess). The default command looks like:

`./leelaz --gtp --lagbuffer 0 --weights ./lznetwork.gz`

After installation, `leelaz` is not in the same directory as `lizzie.jar`, so of course this doesn't work. I was able to work around this just by providing absolute paths.

**Comment by featurecat** [comment]
oh, yikes, I guess that's a mistake I made with the release package. thanks for bringing it to my attention, glad you figured it out.

**Comment by featurecat** [comment]
Update... I looked at the release, and the default config file does have the right path. But if you delete the default config and let Lizzie generate a new one for you, it gets the path wrong. Not sure what the best solution in general here will be. But at least it's not such a big oversight that Lizzie doesn't work out-of-the-box.

**Comment by MortimerMcMire315** [comment]
Oh, interesting. I don't remember deleting the config file, but I did open it up with a text editor at some point. Maybe I messed it up somehow.

Thanks for pointing me in the right direction!

**Comment by toomasr** [comment]
I believe #662 fixes this.
